let handler = async (m, { conn }) => {
    // كل الاوامر ديال DAMAR-MD
    const slides = [
        '.addmetaai : كيزيد Meta AI للكروب',
        '.addprem : كيزيد عضو للبريميوم',
        '.ai-image : كيصنع صورة بالذكاء الاصطناعي',
        '.ailabs : أدوات مختبرات AI',
        '.aimirror : مراية AI كتقلد ستايلك',
        '.aimusic : كيصنع موسيقى بالـ AI',
        '.aljazeera : كيجيب اخبار الجزيرة',
        '.alldownload : تحميل من جميع المواقع',
        '.apk : البحث وتحميل تطبيقات APK',
        '.apkdog : تحميل APK من موقع apkdog',
        '.apkdogsearch : البحث فـ apkdog',
        '.apkdownload : تحميل مباشر APK',
        '.apkmaker : صناعة تطبيق APK',
        '.appteka : متجر التطبيقات',
        '.arabicfont : تغيير الخط للعربي',
        '.artly : رسم بالذكاء الاصطناعي',
        '.autoai : الرد التلقائي بالـ AI',
        '.banchat : حظر الشات',
        '.banuser : حظر مستخدم',
        '.bingimages : البحث عن صور فـ Bing',
        '.bingsearchimg : البحث بالصورة فـ Bing',
        '.brat : نص بستايل brat',
        '.broadcastptv : ارسال رسالة للكل',
        '.capcut-dl : تحميل فيديو CapCut',
        '.capcut : تعديل فيديو CapCut',
        '.capcutdlv3 : تحميل CapCut v3',
        '.carbon : تحويل الكود لصورة',
        '.channel-id : ID ديال القناة',
        '.channel-list : لائحة القنوات',
        '.clearcache : مسح كاش البوت',
        '.cleartmp : مسح الملفات المؤقتة',
        '.cmd-del : مسح امر مخصص',
        '.cmd-list : لائحة الاوامر المخصصة',
        '.cmd-lock : قفل امر',
        '.cmd-set : صناعة امر مخصص',
        '.code2img : تحويل الكود لصورة',
        '.colorize_v2 : تلوين الصور',
        '.couple : ثنائي عشوائي',
        '.creategroup : صناعة كروب',
        '.dafont : البحث عن الخطوط',
        '.dashboard : لوحة تحكم البوت',
        '.deletemsg : مسح رسالة',
        '.deleteplugin : مسح بلاغين',
        '.delprem : حذف من البريميوم',
        '.disk : مساحة التخزين',
        '.dragonball : صور دراغون بول',
        '.editimage : تعديل الصور',
        '.enable : تفعيل ميزة فالكروب',
        '.f-droid : تحميل من F-Droid',
        '.facebook : تحميل من فيسبوك',
        '.fakechat : محادثة مزيفة',
        '.feature : ميزات البوت',
        '.fetch : جلب محتوى من رابط',
        '.firelogo : لوجو بالنار',
        '.flamingtext : نص ملتهب',
        '.fontsearch : البحث عن الخطوط',
        '.gcbot : معلومات كروب البوت',
        '.gen : توليد نص',
        '.getgits : تحميل من Git',
        '.getplugin : تحميل بلاغين',
        '.ghosttag : منشن مخفي',
        '.gif-sticker : تحويل GIF لستيكر',
        '.githubstalk : تتبع حساب GitHub',
        '.githubtrend : الترند فـ GitHub',
        '.gock : لعبة',
        '.group-id : ID ديال الكروب',
        '.group-manage : ادارة الكروب',
        '.group-setcostum : اعدادات الكروب',
        '.grouplist : لائحة الكروبات',
        '.hd : تحسين جودة الصورة',
        '.hidetag : منشن مخفي للكل',
        '.hidetagfakepoll : تصويت مزيف',
        '.horde : توليد صور AI',
        '.ig-post : تحميل منشور انستغرام',
        '.ig-profile : بروفايل انستغرام',
        '.ig : تحميل من انستغرام',
        '.igsearch : البحث فانستغرام',
        '.img2prompt : تحويل الصورة لنص',
        '.imgupload : رفع الصورة',
        '.joinchannel : الدخول لقناة',
        '.kive : بحث Kive',
        '.landsat : صور الاقمار الصناعية',
        '.lang : تغيير اللغة',
        '.list : لائحة',
        '.listpremium : لائحة البريميوم',
        '.lyric : كلمات الاغاني',
        '.main-afk : وضع AFK',
        '.mediafire-dl : تحميل من MediaFire',
        '.mediafire : بحث MediaFire',
        '.mediafiredl : تحميل MediaFire',
        '.menu : القائمة الرئيسية',
        '.msg-to-channel : ارسال رسالة للقناة',
        '.nanobanana : فلتر الموزة',
        '.notoemoji : ايموجي Noto',
        '.owner-exec : تنفيذ امر للمالك',
        '.owner-exec2 : تنفيذ امر 2',
        '.owner-simulate : محاكاة المالك',
        '.owner : معلومات المالك',
        '.pastebindl : تحميل من Pastebin',
        '.pin : تثبيت رسالة',
        '.ping : سرعة البوت',
        '.pint : صور Pinterest',
        '.pinterest : البحث فـ Pinterest',
        '.pixiv : صور Pixiv',
        '.qrcode : صناعة QR Code',
        '.quoted : نسخ الاقتباس',
        '.quran : القرآن الكريم',
        '.quranmp3 : تلاوة mp3',
        '.register : التسجيل فالبوت',
        '.removal : ازالة عضو',
        '.restart : اعادة تشغيل البوت',
        '.revoke : رابط دعوة جديد',
        '.rvo : فتح view once',
        '.savetik : حفظ تيكتوك',
        '.savezip : حفظ كـ zip',
        '.screenshot : لقطة شاشة لموقع',
        '.sdxl : توليد صور SDXL',
        '.searchgroups : البحث عن كروبات',
        '.seerah : السيرة النبوية',
        '.send-to-channel : ارسال للقناة',
        '.sendptvchannel : ارسال PTV للقناة',
        '.sfile : رفع ملف',
        '.sfp : اداة SFP',
        '.ssweb : سكرينشوت لموقع',
        '.ssweb2 : سكرينشوت v2',
        '.sswebv2 : سكرينشوت v3',
        '.sticker : تحويل لستيكر',
        '.tag : منشن للكل',
        '.test : اختبار البوت',
        '.texttrick : حيل النصوص',
        '.tibbi : استشارة طبية',
        '.tiktok : تحميل تيكتوك',
        '.tiktok2 : تحميل تيكتوك v2',
        '.tiktokdown : تحميل بدون علامة',
        '.tiktokstat : احصائيات تيكتوك',
        '.toimg : تحويل ستيكر لصورة',
        '.totalfeatures : عدد الميزات',
        '.totaluser : عدد المستخدمين',
        '.ttdl : تحميل تيكتوك',
        '.ttsanime : تحويل النص لصوت انمي',
        '.twitter : تحميل من تويتر',
        '.unban : فك الباند',
        '.unbanchat : فك باند الشات',
        '.unregister : الغاء التسجيل',
        '.unsplash : صور Unsplash',
        '.url-short : اختصار الروابط',
        '.wallpaper : خلفيات',
        '.wavel : تحويل صوت',
        '.whatsgrouplink : رابط كروب واتساب',
        '.youtubesearch : البحث فاليوتيوب',
        '.ytdl : تحميل يوتيوب',
        '.ytmp3 : تحميل يوتيوب mp3',
        '.ytmp4-gg : تحميل يوتيوب mp4',
        '.ytmp4 : تحميل يوتيوب فيديو',
        '.ytpost : منشور يوتيوب',
        '.yts : بحث يوتيوب'
    ]

    const finalMsg = `✅ *هادو هما اوامر خاصين بي بوت DAMAR-MD*`

    // الرسالة الاولى
    let msg = await conn.sendMessage(m.chat, { text: `📚 ${slides[0]}` })

    let i = 1
    const max = slides.length

    const interval = setInterval(async () => {
        if (i >= max) {
            clearInterval(interval)
            // فاللخر
            return conn.sendMessage(m.chat, { text: finalMsg }, { quoted: msg })
        }

        try {
            await conn.sendMessage(m.chat, {
                text: `📚 ${slides[i]} [${i+1}/${max}]`,
                edit: msg.key
            })
            i++
        } catch(e) {
            clearInterval(interval)
        }
    }, 4000) // كل 4 ثواني
}

handler.help = ['تعليم']
handler.tags = ['info']
handler.command = ['تعليم', 'taalim']
export default handler